add: request, pagination
9999kDMG/java-shareit pull request #3
Opened 2023-02-28 13:35 UTC by 9999kDMG

2023-03-01 18:20 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-03-01 18:20 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private Pageable getPageOrThrow(Integer from, Integer size) {
Этот приватный метод написан дважды.
И при этом отличаются одной строчкой! 

Это ошибка/не ошибка ?

Должна быть одна реализация, стараемся не писать дважды одно и тоже - переиспользуем уже написанный код.

2023-03-01 18:20 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +        return ItemRequestMapper.toItemRequestDto(itemRequestRepository.save(itemRequest));
- перед `return` желателен отступ - пустая строка, чтобы визуально отделить завершение метода
- главное действие - сохранение не прячем в строке маппинга, оно достойно отдельной строки кода, чтобы бросалось в глаза
- статические методы можно предварительно заимпортить, чтобы получился более короткий и удобочитаемый код.

```
    public ItemRequestDto createRequest(int userId, ItemRequestDto itemRequestDto) {
        User user = userService.getUserById(userId);
        ItemRequest itemRequest = toItemRequest(itemRequestDto);
        itemRequest.setUser(user);

        ItemRequest savedRequest = itemRequestRepository.save(itemRequest);

        return toItemRequestDto(savedRequest);
    }
```

2023-03-02 12:30 UTC, 9999kDMG commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private Pageable getPageOrThrow(Integer from, Integer size) {
метод перенесен в utils.

2023-03-02 18:19 UTC, FanaticFiz approved these changes

2023-03-03 18:20 UTC, merged